# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapi', '0002_auto_20170611_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='user',
        ),
        migrations.RemoveField(
            model_name='servicearea',
            name='user',
        ),
    ]
